#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# ~/.huskyrc
# This loads nvm.sh and sets the correct PATH before running hook
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

npx pretty-quick --staged --pattern "**/*.*js"
npx pretty-quick --staged --pattern "**/*.*ts"
npx pretty-quick --staged --pattern "**/*.*html"
npx pretty-quick --staged --pattern "**/*.*scss"
npx pretty-quick --staged --pattern "**/*.*json"
npx nx affected:lint --parallel
